version: 1
disable_existing_loggers: False
formatters:
  basic:
    (): __main__.OneLineExceptionFormatter
    format: "%(message)s"
  pipe:
    format: "%(asctime)s|%(name)s|%(levelname)s|%(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
    stream: ext://sys.stdout

  file_handler:
    () : __main__.create_app_folder_log_handler
    level: NOTSET
    formatter: pipe
    filename: tasks.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root:
  level: DEBUG
  handlers: [console_handler, file_handler]

loggers:
  CommandFactory:
    level: INFO
    handlers: [console_handler, file_handler]
    propogate: no
  LayeredSettingsProvider:
    level: INFO
    handlers: [console_handler, file_handler]
    propogate: no
  TaskAttributeFilter:
    level: INFO
    handlers: [console_handler, file_handler]
    propogate: no
  TaskIndexFilter:
    level: INFO
    handlers: [console_handler, file_handler]
    propogate: no
  TaskNameFilter:
    level: INFO
    handlers: [console_handler, file_handler]
    propogate: no