#!/bin/bash

set -o pipefail

coverage=$(bin/run-tests.sh 2>&1 | sed -n 's/^TOTAL[[:blank:]]\+[0-9]\+[[:blank:]]\+[0-9]\+[[:blank:]]\+\([0-9]\+\)%$/\1/p')
exit_code=${PIPESTATUS[0]}

if [[ $exit_code -ne 0 ]]; then
    echo "Failed running unit tests"
    exit $exit_code
else
    echo "Unit tests passed"
fi

if [[ $coverage -lt 90 ]]; then
    echo "Unit test coverage: $coverage%, less than 90% threshold"
    exit 1
else
    echo "Unit test coverage: $coverage%, acceptable"
fi

exit 0
