#!/bin/bash

bin/run-tests.sh > /dev/null 2>&1
exit_code=${PIPESTATUS[0]}

if [[ $exit_code -ne 0 ]]; then
    echo "Failed running unit tests"
    exit $exit_code
else
    echo "Unit tests passed"
fi

exit 0
