#!/bin/bash

exit 0


commit_message_file="$1"

if [ $# -gt 1 ]; then
	commit_message_type="$2"
else
	commit_message_type=''
fi

if [ $# -gt 2 ]; then
	sha="$3"
else
	sha=''
fi

branch_name=$(git branch | grep '\*')
branch_name=${branch_name:2:100}
ticket_name=$(echo "$branch_name" | sed -n 's/\([[:alnum:]]\+\)_.\+/\1/p' )
commit_message=$(cat $commit_message_file)

#echo "Commit message file: $commit_message_file"
#echo "Commit message type: $commit_message_type"
#echo "Sha: $sha"
#echo "Branch: [$branch_name]"
#echo "Ticket: [$ticket_name]"
#echo "Commit message: $commit_message"

case $commit_message_type in
	'commit')
		;;
	'merge')
		;;
	'message')
		commit_message="$ticket_name: $commit_message"
		;;
	'squash')
		;;
	'template')
		;;
	*)
		commit_message="$ticket_name: $commit_message"
		;;
esac

echo "$commit_message" > $commit_message_file
